force-app/main/default/objects/Link__c/Link__c.object-meta.xml
<CustomObject>
    <label>Link</label>
    <nameField>
        <label>Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Link__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Toolbox</fullName>
                <default>true</default>
                <label>Toolbox</label>
            </value>
            <value>
                <fullName>Company Links</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Link__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <inlineHelpText>Icon name from Lightning Design System -&gt; https://www.lightningdesignsystem.com/icons/</inlineHelpText>
    <label>Icon</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Link__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <formula>HYPERLINK( URL__c , Name )</formula>
    <label>Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Link__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LinkController.cls
public without sharing class LinkController {
    
    @AuraEnabled
    public static List<Link__c> getLinks() {
       System.debug('LinkController > getLinks');
       return [SELECT Id, Name, Category__c, URL__c, Icon__c FROM Link__c WHERE Active__c=true];
    } 
    
    @AuraEnabled
    public static List<Link__c> getLinksByCategory(String targetCategory) {
       System.debug('LinkController > getLinks - targetCategory: ' + targetCategory);
       return [SELECT Id, Name, Category__c, URL__c, Icon__c FROM Link__c WHERE Active__c=true AND Category__c=:targetCategory];
    } 
    
} // end LinkController